[indicator]

# padding = { open = "█", close = "" }
padding = { open = "█", close = "█" }

[filetype]

rules = [
    # Hidden files
    { url = "*", is = "hidden", fg = "#9DA9A0" },

    # Hidden directories
    { url = "*/", is = "hidden", fg = "#9DA9A0", bold = true},

    # Directories
    { url = "*/", fg = "green", bold = true},

]
