[mgr]
# cwd = { bg = "red", fg = "green" }

[mode]
normal_main = { bg = "#93B259", fg = "#FDF6E3", bold = true }
normal_alt = { bg = "#E6E2CC", fg = "#829181" }
select_main = { bg = "red", fg = "white", bold = true }
select_alt = { bg = "#E6E2CC", fg = "#829181" }
unset_main = { bg = "red", fg = "white", bold = true }
unset_alt = { bg = "#E6E2CC", fg = "#829181" }

[indicator]
padding = { open = "█", close = "" }
# padding = { open = "█", close = "█" }

[status]
overall = { bg = "#F4F0D9", fg = "#939F91" }
sep_left = { open = "", close ="" }
sep_right = { open = "", close ="" }

[filetype]
rules = [
    # Hidden files
    { url = "*", is = "hidden", fg = "#9DA9A0" },

    # Hidden directories
    { url = "*/", is = "hidden", fg = "#9DA9A0", bold = true},

    # Directories
    { url = "*/", fg = "green", bold = true},

]

# https://raw.githubusercontent.com/sxyazi/yazi/refs/heads/main/yazi-config/preset/theme-light.toml
[icon]
prepend_dirs  = [
	{ name = ".config", text = "", fg = "#9DA9A0" },
	{ name = ".git", text = "", fg = "#9DA9A0" },
	{ name = ".github", text = "", fg = "#9DA9A0"},
	{ name = ".npm", text = "", fg = "#9DA9A0" },
	{ name = "Desktop", text = "", fg = "green" },
	{ name = "Development", text = "", fg = "green" },
	{ name = "Documents", text = "", fg = "green" },
	{ name = "Downloads", text = "", fg = "green" },
	{ name = "Library", text = "", fg = "green" },
	{ name = "Movies", text = "", fg = "green" },
	{ name = "Music", text = "", fg = "green" },
	{ name = "Pictures", text = "", fg = "green" },
	{ name = "Public", text = "", fg = "green" },
	{ name = "Videos", text = "", fg = "green" },
]

prepend_conds = [
	{ if = "dir", text = "", fg = "green" },
]
